var keyword_collect = [
                            "18+","16+","movies","Nano","animation","drama ","drama movie","tool",
		"Adsense","Ajax","âm nhạc","ảnh","audio","axit","Ăn chơi","Ảnh nóng","Alexa","Ảnh vui","Alexa",
		"bài gần đây","bài liên quan","bán dâm","banner","Bill Gates","blogger","blogspot","bookmark",
		"cafe","cấu hình","chơi đàn","chồng","clip","cơ bản","cơ sở","con gái","công cụ","CSS","cua gái","comment","Chuyện ấy","cute girl","Crack","cine",
		"đại gia","đàn bà","đàn ông","Dashboard","Desktop","địa chỉ ip","điện thoại","domain","download","down nhạc","design","DVDrip","HDrip",
		"editor","email","Explorer","Ebooks",
		"feedburner","file","FireFox","flash","Form comment",
		"GA","gà cáo","ghita","Gmail","Google","google.com","GTalk","guitar","giới tính","giới trẻ",
		"Hà Nội","hacking","hacker","hexa","hiếp dâm","hình","hình sự","Hitler","Hoa Kỳ","hóa học","học sinh","HTML","Huế","Hot girl","Hot Link","Học đường","học trò","Hài hước",
		"image","Internet","IPhone",
		"java","javascript","jquery","js","json",
		"kinh tế","khoa học","kiến thức","kinh nghiệm","keygen","kiếm tiền","kontactr",
		"làm tình","lập trình","Linux","love","Lưu Diệc Phi","lời khuyên",
		"mạng cộng đồng","Media","menu","Mobile","Mozilla","MP3","MP4","MS Office","mua dâm","music","Mỹ","Mẹo","Mootools","Mediafire","Megaupload","Máy tính",
		"Nga","nghệ thuật","ngoại tình","nhắn tin","nhật ký","nick","Nghệ thuật sống","Notrasdamus","Navbar","Nude","Ngày ấy","ngộ nghĩnh",
		"Office","Opera","office",
		"Phi Phi","phụ nữ","Portable","Phim hot","Photoshop","papazazi","phim","Phim bộ",
		"Sài Gòn","sát thủ","sinh học","sinh lý","sinh viên","SMS","soft","sothink","Sex","sofwware","scandal",
		"Tây Ninh","tên miền","thất tình","thư điện tử","thủ thuật","thương mại","tìm kiếm","tin tức","tình dục","tình yêu","toán","tool","top","TP HCM","TP. Hồ Chí Minh","Trảng Bàng","Trung","tiện ích","tỏ tình","teen","tự sướng","template","thumbnail","truyện cười","truyện ngắn","thằng nhỏ","trẻ em",
		"Users online","Using",
                            "Rank","Read more","Recent posts","Related posts","Rapidshare",
		"vật lý","video","Việt Nam","Vista","vợ",
		"web","widget","window",
		"xác suất","XXX","xe độ","xa xỉ",
		"Yahoo","Yahoo 360","Yahoo Mail","Yahoo Mash","Yahoo Messenger","yahoo.com","yêu đương","Youtube","youtube.com"
		]

